server:
  port: 8911
spring:
  application:
    name: messagecontent    # 项目名称尽量用小写
eureka:
  client:
    serviceUrl:
      defaultZone: http://ds:8761/eureka/ ,http://ds:8762/eureka/   # 指定注册中心的地址
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: ds