server:
  port: 8903
spring:
  application:
    name: messagecontent    # 项目名称尽量用小写
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8900/eureka/    # 指定注册中心的地址
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: localhost