spring:
  application:
    name: zuulapigatewary
server:
  port: 8999
eureka:
  client:
    serviceUrl:
      defaultZone: http://ds:8761/eureka/,http://ds:8762/eureka/
  instance:
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: ds